setwd("~/Documents/mountain-hill")
install.packages("gdata")
require(gdata)
hills = read.xls("doBIH_v15.1.xls")
require(dplyr)
heights<-select(hills, Feet)
hist(hills$Feet, breaks=15)
mean(hills$Feet)
min(hills$Feet)
quantile(hills$Feet)   
qqplot(hills$Feet)
install.packages("nortest")
library(nortest)
ad.test(hills$Feet)
qqnorm(hills$Feet)
qqline(hills$Feet)

mountains = read.xls("world100.xls")
hist(mountains$Elevation, breaks=5)
hist(mountains$Prominence, breaks=10)


colorado = read.xls("colorado.xls")
hist(colorado$Elevation2, breaks=80)
hist(mountains$Prominence, breaks=10)
